### PR TITLE
fixes social svgs

### LINKED ISSUE #75: SVG Social Media Logos Not Centered
The social media SVGs seem to render with logos not centered within the logo circle. As measured in MS Paint roughly from the four cardinal directions in to the main part of the logo in question, buffers seem to be about:

Facebook: 6px 12px 11px 7px
Instagram: 6px 7px 7px 6px
Twitter: 8px 9px 9px 7px
Medium: 8px 7px 8px 6px
YouTube:  6px 11px 8px 9px

It makes them some of them visually jarring (such as YouTube) or at least gives them a mild "weird" look (like the mildly uncentered ones like Instagram) because they can be seen to be not centered easily enough without measuring.

image

### PR DESCRIPTION
**Pull request by abea**
Closes #75

### CODE REVIEW

**Comment by csell5** [comment]
@abea Thank you for joining us here and all the help! Can you look at that YouTube one some more? It's either me or that thing is still really off centered.

**Comment by brandonmartinez** [comment]
@abea are you using a vector editing app to make the changes? Would you possibly be able to use the official YouTube icon in the SVG instead of the old "play" icon we've had? YouTube has an EPS/AI file available that can be used here: https://www.youtube.com/about/brand-resources/#logos-icons-colors (it's about midway down).

If you're not able to make the SVG, I'd be more than happy to assist.

I would also recommend bumping the Facebook and Instagram icon size just a tad so the weight is even with other icons.

Thanks for helping with this!

**Comment by abea** [comment]
@csell5 My pleasure. I'll check out the YouTube one, or try the alternative one Brandon mentioned.

@brandonmartinez I'm using Boxy SVG to do basic repositioning, but I don't think it converts .eps to SVG well. If you don't mind, please do drop an SVG version in here and I'll get that swapped out.

**Comment by brandonmartinez** [comment]
@abea would this work (thanks wikipedia!): https://en.wikipedia.org/wiki/File:Logo_of_YouTube_(2015-2017).svg#/media/File:YouTube_light_icon_(2017).svg

If not, I'll cut one in the circle :)

**Comment by saragibby** [comment]
@abea adding a `wip` label to this one as you and @brandonmartinez work through it. Let me know how I can help. And huge thanks for jumping in to tackle this one!

**Comment by abea** [comment]
Thanks, Sara. Apologies for the radio silence. It was a busy last week before Christmas then traveling. I'll be back in action this week.


On Fri, Dec 27, 2019 at 9:09am, Sara Gibbons < notifications@github.com [notifications@github.com] > wrote:
@abea [https://github.com/abea] adding a wip label to this one as you and @brandonmartinez [https://github.com/brandonmartinez] work through it. Let me know how I can help. And huge thanks for jumping in to tackle this one!

**Comment by abea** [comment]
Ready for a new review.

**Comment by abea** [comment]
By the way, I'm getting errors from `components/Header/MessageBar.js` (`Failed prop type: Link: unknown props found: onClick`) and `lib/withApolloClient.js` (`Error while running `getDataFromTree` { Error: Network error: Only absolute URLs are supported`) while running locally.

**Comment by brandonmartinez** [comment]
These look pretty good to me!

**Comment by saragibby** [comment]
@abea no apologies needed! We are grateful for giving us your time and contributing. These changes look great and thanks for getting these fixed up.

**Pull request merged**
