### PR TITLE
clean up routing and add redirects for state index pages

### PR DESCRIPTION
**Pull request by saragibby**

### CODE REVIEW

**Comment by csell5** [comment]
#### 📝Changed routes:


| [**/tx/2021**](https://that-website-git-sg-one-daymore-routing.that-conference.now.sh/tx/2021) | [**/tx**](https://that-website-git-sg-one-daymore-routing.that-conference.now.sh/tx) |
|:-:|:-:|
|<a href="https://that-website-git-sg-one-daymore-routing.that-conference.now.sh/tx/2021">Screenshot of /tx/2021</a><br /><sup><a href="https://images.weserv.nl?url=https://s.microlink.io/tIXyc_U3NN7YvkqKE9SiCOlh5hs_.png">(view full size)</a> |<a href="https://that-website-git-sg-one-daymore-routing.that-conference.now.sh/tx">Screenshot of /tx</a><br /><sup><a href="https://images.weserv.nl?url=https://s.microlink.io/tTsj3zUgrsf7L_b634bhi7J2sH8_.png">(view full size)</a> |



| [**/wi/2020**](https://that-website-git-sg-one-daymore-routing.that-conference.now.sh/wi/2020) | [**/wi/2021/\[markdown\]**](https://that-website-git-sg-one-daymore-routing.that-conference.now.sh/wi/2021/[markdown]) |
|:-:|:-:|
|<a href="https://that-website-git-sg-one-daymore-routing.that-conference.now.sh/wi/2020">Screenshot of /wi/2020</a><br /><sup><a href="https://images.weserv.nl?url=https://s.microlink.io/2TtpRq3esy12yBN4ZtV8u_dpdoE_.png">(view full size)</a> |<a href="https://that-website-git-sg-one-daymore-routing.that-conference.now.sh/wi/2021/[markdown]">Screenshot of /wi/2021/[markdown]</a><br /><sup><a href="https://images.weserv.nl?url=https://s.microlink.io/u6Mm_GxUtXW4Y1VAae6p6YTZTZM_.png">(view full size)</a> |



| [**/wi/2021/become-a-partner**](https://that-website-git-sg-one-daymore-routing.that-conference.now.sh/wi/2021/become-a-partner) | [**…21/call-for-counselors**](https://that-website-git-sg-one-daymore-routing.that-conference.now.sh/wi/2021/call-for-counselors) |
|:-:|:-:|
|<a href="https://that-website-git-sg-one-daymore-routing.that-conference.now.sh/wi/2021/become-a-partner">Screenshot of /wi/2021/become-a-partner</a><br /><sup><a href="https://images.weserv.nl?url=https://s.microlink.io/9xrypSohXyEWD5oWzBEdwLHG9Ew_.png">(view full size)</a> |<a href="https://that-website-git-sg-one-daymore-routing.that-conference.now.sh/wi/2021/call-for-counselors">Screenshot of /wi/2021/call-for-counselors</a><br /><sup><a href="https://images.weserv.nl?url=https://s.microlink.io/0r8XbgrR9MOYAo5BlRJfv1oWt9k_.png">(view full size)</a> |



And 16 other routes:
- [**/wi/2021/counselor-agreement**](https://that-website-git-sg-one-daymore-routing.that-conference.now.sh/wi/2021/counselor-agreement)
- [**/wi/2021/counselor-selection-process**](https://that-website-git-sg-one-daymore-routing.that-conference.now.sh/wi/2021/counselor-selection-process)
- [**/wi/2021/counselor-start**](https://that-website-git-sg-one-daymore-routing.that-conference.now.sh/wi/2021/counselor-start)
- [**/wi/2021/important-dates**](https://that-website-git-sg-one-daymore-routing.that-conference.now.sh/wi/2021/important-dates)
- [**/wi/2021**](https://that-website-git-sg-one-daymore-routing.that-conference.now.sh/wi/2021)
- [**/wi/2021/jobs**](https://that-website-git-sg-one-daymore-routing.that-conference.now.sh/wi/2021/jobs)
- [**/wi/2021/partners**](https://that-website-git-sg-one-daymore-routing.that-conference.now.sh/wi/2021/partners)
- [**/wi/2021/plan-your-trip**](https://that-website-git-sg-one-daymore-routing.that-conference.now.sh/wi/2021/plan-your-trip)
- [**/wi/2021/prospectus**](https://that-website-git-sg-one-daymore-routing.that-conference.now.sh/wi/2021/prospectus)
- [**/wi/2021/session/create**](https://that-website-git-sg-one-daymore-routing.that-conference.now.sh/wi/2021/session/create)
- [**/wi/2021/speakers**](https://that-website-git-sg-one-daymore-routing.that-conference.now.sh/wi/2021/speakers)
- [**/wi/2021/tickets**](https://that-website-git-sg-one-daymore-routing.that-conference.now.sh/wi/2021/tickets)
- [**/wi/2021/voting**](https://that-website-git-sg-one-daymore-routing.that-conference.now.sh/wi/2021/voting)
- [**/wi/2021/voting/review**](https://that-website-git-sg-one-daymore-routing.that-conference.now.sh/wi/2021/voting/review)
- [**/wi/2021/voting/vote**](https://that-website-git-sg-one-daymore-routing.that-conference.now.sh/wi/2021/voting/vote)
- [**/wi**](https://that-website-git-sg-one-daymore-routing.that-conference.now.sh/wi)



Commit f5d85a8e9107ce5de02bd83ef40e33e91836acf9 (https://that-website-git-sg-one-daymore-routing.that-conference.now.sh).

**Comment by saragibby** [comment]
@kburnell here is the rest of the routing changes for the one day event page. Should move everything to the right spots now so that `/wi/2020` renders the one day event page instead of `tx/2021`

**Comment by csell5** [comment]
why not make it dynamic?

**Comment by saragibby** [comment]
All for the dynamic. To do that I need some support from the backend. I was trying to get us to the first point of being able to have something to launch. Happy to dig into the getting the pieces more dynamic anytime.

**Pull request merged**
