### PR TITLE
Add breakpoint for homepage action button width, Fixes #335

### LINKED ISSUE #335: Horizontal Scroll on front page for some breakpoints
## Issue
Horizontal Scroll on front page for browsers between 1140 & 1260px wide

## Steps to Reproduce
Resize the browser window to various widths

## What you see
The Hero__Main will start to cause horizontal scroll issues between the xlarge and large breakpoints.

## What you should probably see
No horizontal scrolling thanks to responsive design

### PR DESCRIPTION
**Pull request by tsidel**
Fix for issue #335 

The fixed min-width of the action buttons wasn't allowing the Hero__Main section to be fully responsive.

### CODE REVIEW

**Comment by saragibby** [comment]
Super pumped you are looking into this issue, it drives me equally crazy to see the horizontal scroll 😄 I noticed the button text wrapping, wondering if we should stack that section sooner to avoid the text wrapping, what do you think?
image

**Comment by tsidel** [comment]
I could also fix the line height, so the wrapping doesn't look as bad.

Screen Shot 2020-01-29 at 7 37 03 PM

I think we'd only be able to stack them sooner if we add an additional break point that's between xlarge and large break points 
`  large: 1140,
  xlarge: 1500,`

**Comment by saragibby** [comment]
@tsidel good point about needing the additional break, seems like that might be the way to go. What do you think about be a good size to break at?

**Comment by tsidel** [comment]
Hi @saragibby - I went ahead and created a new breakpoint between xlarge and large (called it 'larger' for lack of a better idea). It allows the 3 buttons to stay the same static width as the rest of the buttons, but becomes responsive at 1360px, and things start stacking at that point.  Hopefully this is helpful.

**Pull request merged**
