### PR TITLE
resized and compressed images

### PR DESCRIPTION
**Pull request by saragibby**

### CODE REVIEW

**Comment by csell5** [comment]
#### 📝Changed routes:


| [**/wi**](https://that-website-git-sara-compress-images.that-conference.now.sh/wi) |
|:-:|
|<a href="https://that-website-git-sara-compress-images.that-conference.now.sh/wi">Screenshot of /wi</a><br /><sup><a href="https://images.weserv.nl?url=microlink-screenshot.nyc3.digitaloceanspaces.com/0uLc5dH_7jlzARnIJJyT2rleAe4_">(view full size)</a> |







Commit 64292393eb17c50cbe8d366f0a52d84a7eb0541a (https://that-website-git-sara-compress-images.that-conference.now.sh).

**Comment by saragibby** [comment]
@csell5 @brettski @kburnell compressed images. If you can give the PR deploy site a run through to make sure all look good I'd appreciate.

**Comment by GeekOnCoffee** [comment]
Looks good to me!

**Comment by brettski** [comment]
This looks good. The page size is down to 2.1MB. The Mess Hall photo at the bottom which was 3MB is now 361k. The images still look clear. I say this is good to go.

**Comment by saragibby** [comment]
I sent everything through: https://compressjpeg.com/
The photos I resized before I compressed, the illustrations lost some clarity when I resized before I compressed so I just compressed them. We can prolly get those smaller, will just need Brandon to work his magic.

**Pull request merged**
