### PR TITLE
added linting on compile

### PR DESCRIPTION
**Pull request by kburnell**

### CODE REVIEW

**Comment by kburnell** [comment]
@brettski running `npm run lint` locally didn't find them

**Comment by brettski** [comment]
Now runs `npm run validate` on build

**Comment by kburnell** [comment]
@brettski next.config.js is in the .eslintignore file

**Comment by brettski** [comment]
This was done as Zeit changes this file in some way and it was failing when tested.

**Comment by kburnell** [comment]
npm run validate does not find them locally either

**Comment by kburnell** [comment]
@brettski so on the server it needs to use the ignore file as well

**Comment by brettski** [comment]
My understanding is that it is.

**Comment by kburnell** [comment]
It can't be if it blew up because of the issues in next.config.js when I tried to deploy

**Comment by brettski** [comment]
I understand what you are saying, but it doesn't make sense. :)

**Comment by kburnell** [comment]
@brettski since that is kind of outside the scope of my change can you approve this PR please?

**Pull request merged**
