### PR TITLE
Partner goodness

### PR DESCRIPTION
**Pull request by saragibby**
- add more detail into partner profile page
- wire up the partner profile to the data from graph
- move parter profile pages to root
- add root partners page to list all parters evah

### CODE REVIEW

**Comment by csell5** [comment]
#### 📝Changed routes:


| [**/partner/\[slug\]**](https://that-website-git-sg-partners-page-magic.that-conference.now.sh/partner/[slug]) | [**/partners**](https://that-website-git-sg-partners-page-magic.that-conference.now.sh/partners) |
|:-:|:-:|
|<a href="https://that-website-git-sg-partners-page-magic.that-conference.now.sh/partner/[slug]">Screenshot of /partner/[slug]</a><br /><sup><a href="https://images.weserv.nl?url=https://microlink.nyc3.digitaloceanspaces.com/LIzRIlIlXd6HtwkmvzJ2qKkB1BU_">(view full size)</a> |<a href="https://that-website-git-sg-partners-page-magic.that-conference.now.sh/partners">Screenshot of /partners</a><br /><sup><a href="https://images.weserv.nl?url=https://microlink.nyc3.digitaloceanspaces.com/tPgVX2_eTOcBn2sSi_S4U4tkYy4_">(view full size)</a> |



| [**…elor-selection-process**](https://that-website-git-sg-partners-page-magic.that-conference.now.sh/wi/counselor-selection-process) | [**/wi/partners**](https://that-website-git-sg-partners-page-magic.that-conference.now.sh/wi/partners) |
|:-:|:-:|
|<a href="https://that-website-git-sg-partners-page-magic.that-conference.now.sh/wi/counselor-selection-process">Screenshot of /wi/counselor-selection-process</a><br /><sup><a href="https://images.weserv.nl?url=https://microlink.nyc3.digitaloceanspaces.com/gAp_885ZAcyiWBHiK3N2Jo4zqfA_">(view full size)</a> |<a href="https://that-website-git-sg-partners-page-magic.that-conference.now.sh/wi/partners">Screenshot of /wi/partners</a><br /><sup><a href="https://images.weserv.nl?url=https://microlink.nyc3.digitaloceanspaces.com/2i1b_bvg85nhcLv4hK39lutQR1U_">(view full size)</a> |





1 deleted route:
- **/wi/partner/[slug]**

Commit 560b032a152b59a07b699da67dcd1a147571275f (https://that-website-git-sg-partners-page-magic.that-conference.now.sh).

**Comment by saragibby** [comment]
**re: New Relic logo...**
Something seems off with that image file, not sure what yet but it doesn't seem to load anywhere we reference it on our site. Is there something different about that file? Is it typical of what we can expect all partner logos to be?

**re: empty sections...**
From a user/camper perspective seeing headers with no data isn't a great experience and makes the site appear broken. I assumed moving forward with sponsors we would make then aware outside of the site what information we could include. Eventually maybe wiring up a way for the to see + edit those sections themselves maybe. Past sponsors though, not sure how much we want to fill in there. 

**re: maximum # of sessions...**
There may be a point where is looks like too many, but until we get data in it's really a guess. It will be easier to figure out how to handle those when we hit them. 

**re: members displaying...**
Right now I'm just displaying the members I get from graph, assuming the `isPartnershipContact` has been checked. If not and we need to do it on the front end, easy enough.

**re: sessions displaying...**
Same here, assume the `isSponsored` check is happening on the back end and display all sessions it gives me. Easy to handle on front end if we need to.

**Comment by brettski** [comment]
@saragibby I am at a loss with the New Relic logo. I uploaded a new png, issue remained. Created an SVG and uploaded, issue remains. Perhaps a Brave issue. Works as expected in Safari and Chrome

**Comment by brettski** [comment]
Well Brandon figured it out. It was Brave blocking the image thinking it was a tracking image as the name contained 'new relic'. updata logo name to nr.svg and all is as expected

**Pull request merged**
