### PR TITLE
fix up important dates page

### LINKED ISSUE #546: /wi/2021/important-dates not displaying correctly
The page, https://www.thatconference.com/wi/2021/important-dates is not displaying correctly. It's seems only the mobile view is showing. When the page is wide it displays a blue background color. When the page is made narrow the list of milestones do display. 

.

Wide view:
image

Narrow view:
image

### PR DESCRIPTION
**Pull request by saragibby**
### Description
Updates the important dates page to render dates properly. 
Stying of page and timeline section further refined as part of this work. 

Fixes #546

### Screenshots (if appropriate):
image

### Types of changes
- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)

### How Has This Been Tested?
Running app locally, testing through Chrome, Brave and Safari on multiple size windows. 

### Checklist:
- [ ] I have updated the documentation if necessary
- [ ] I have updated the stories as necessary
- [ ] I have updated the specs necessary

### CODE REVIEW

**Comment by saragibby** [comment]
ping @ThatConference/that-team for a review

**Comment by csell5** [comment]
#### 📝Changed routes:


| [**/wi/2021/important-dates**](https://that-website-git-sara-546fix-important-dates-page.that-conference.now.sh/wi/2021/important-dates) |
|:-:|
|<a href="https://that-website-git-sara-546fix-important-dates-page.that-conference.now.sh/wi/2021/important-dates">Screenshot of /wi/2021/important-dates</a><br /><sup><a href="https://images.weserv.nl?url=https://s.microlink.io/_5JORO3Tyyh5h0q9gXoGIcEg8CA_.png">(view full size)</a> |







Commit 5859af4d512a3f1eb5158d7657cde4792ff5f223 (https://that-website-git-sara-546fix-important-dates-page.that-conference.now.sh).

**Comment by saragibby** [comment]
ping @ThatConference/that-team for review

**Review by csell5 — CHANGES_REQUESTED** [review]
please rebase on the latest.

**Review by csell5 — APPROVED** [review]

**Pull request merged**
