### PR TITLE
Update for Slug Scalar, tweak message

### PR DESCRIPTION
**Pull request by brettski**
Same change as #499 updating site to work with new scalar Slug
Updates site messaging

### CODE REVIEW

**Comment by kburnell** [comment]
How is this different than pr 499?

**Comment by brettski** [comment]
https://github.com/ThatConference/that-website/pull/500#issuecomment-640238845

One into master and one into our feature branch

**Comment by kburnell** [comment]
If you do a PR against both master and feature with the same changes it will cause a merge issue when feature is merged to master.  Typical flow would be to submit your PR agains master and once it is merged then pull latest master updates in to feature.

**Comment by brettski** [comment]
Cancelling

**Pull request closed without merging**
