### PR TITLE
add start of blog and holiday buying guide post

### PR DESCRIPTION
**Pull request by saragibby**

### CODE REVIEW

**Comment by csell5** [comment]
#### 📝Changed routes:


| [**/wi/blog/\[post\]**](https://that-website-git-sara-add-holiday-buying-guide.that-conference.now.sh/wi/blog/[post]) |
|:-:|
|<a href="https://that-website-git-sara-add-holiday-buying-guide.that-conference.now.sh/wi/blog/[post]">Screenshot of /wi/blog/[post]</a><br /><sup><a href="https://images.weserv.nl?url=microlink.nyc3.digitaloceanspaces.com/wfDJKOZjyFtrurn_Zgmk28glVsk_">(view full size)</a> |







Commit 6a9ec38f379b7271ebccbf0b580105ba58fff63e (https://that-website-git-sara-add-holiday-buying-guide.that-conference.now.sh).

**Comment by saragibby** [comment]
Holiday blog post https://that-website-git-sara-add-holiday-buying-guide.that-conference.now.sh/wi/blog/that-2019-holiday-buying-guide

**Comment by saragibby** [comment]
@kburnell I didn't want to build out the blog listing/landing page right now so I was thinking either:
1. no menu/nav from site to the page
2. add a link in the top message bar to it
Then later when we have time we can circle back around and build out the landing page. 

Goal here is to get it live so that Brandon and link to it from the socials. Talk to me... what are your thoughts?

**Comment by kburnell** [comment]
@saragibby either works was just clarifying that there wasn't supposed to be a link in the PR.

**Pull request merged**
