### PR TITLE
enables ac tracking and email signup modal

### PR DESCRIPTION
**Pull request by csell5**
Brings back in Active Campaign to the website.
* enables the newsletter signup on only the index page.
* enables ac tracking.

### CODE REVIEW

**Comment by csell5** [comment]
#### 📝Changed routes:


| [**/wi**](https://that-website-git-clark-featureaddac.that-conference.now.sh/wi) |
|:-:|
|<a href="https://that-website-git-clark-featureaddac.that-conference.now.sh/wi">Screenshot of /wi</a><br /><sup><a href="https://images.weserv.nl?url=microlink.nyc3.digitaloceanspaces.com/UM4Qu2f_GpGvuU9_Rt0I2SzKPLg_">(view full size)</a> |







Commit 25632f7029cf8fb87f7304ea0784a05ef566e700 (https://that-website-git-clark-featureaddac.that-conference.now.sh).

**Comment by saragibby** [comment]
Looks like the signup in the landing page and footer isn't working with this change. Also, after signing up it takes you to a blank page that says "Thanks for signing up". That's probably from the changes I did to support the signup keeping the user on page and rendering that response in place of the form. `NewsletterSignUpForm` has all the magic for the signup form.

**Comment by csell5** [comment]
I didn't touch that. this adds the modal for first time visitors on the index page.

**Comment by saragibby** [comment]
Maybe not this change, something along the way looks like it broke that form. Currently broke on the live site. Assumed it was the additional embed here from AC. I can dig in.

**Pull request merged**
