### PR TITLE
Correct issue with unknown routes causing http 502

### PR DESCRIPTION
**Pull request by brettski**

### CODE REVIEW

**Comment by csell5** [comment]
#### 📝Changed routes:


| [**/_error**](https://that-website-git-brettski-610502-error.that-conference.now.sh/_error) |
|:-:|
|<a href="https://that-website-git-brettski-610502-error.that-conference.now.sh/_error">Screenshot of /_error</a><br /><sup><a href="https://images.weserv.nl?url=https://s.microlink.io/gabU5EEEBFTjBTWLJAe1o_qf2G4_.png">(view full size)</a> |







Commit 7d9ca40c972a3da4ea8185d458215bc2477e5eae (https://that-website-git-brettski-610502-error.that-conference.now.sh).

**Review by csell5 — COMMENTED** [review]
I take it this is to better debug the SSR side of things?

**Review by csell5 — CHANGES_REQUESTED** [review]
@brettski what's the deal with this PR?

**Comment by brettski** [comment]
Fixing #610 or part of what I identified for it. I don't recall it's state.

**Comment by csell5** [comment]
@brettski do we need the console statements? If not, let's remove them.

**Comment by brettski** [comment]
I honestly don't remember where this was left at. I know the one line was causing 500's, though I am thinking the console statements were there for further testing on other areas which may be causing them. I'll get this cleaned up to at least fix the one finding.

**Pull request closed without merging**
